#+TITLE: Org Tweaks
#+AUTHOR: Break Yang
#+STARTUP: showall

* Key Bindings

| Bindings | Description                                       |
|----------+---------------------------------------------------|
| C-c a    | Org Agenda                                        |
| C-c o    | Main organizer file                               |
| C-c c    | Capture                                           |
| C-c '    | Create a new buffer to edit the source code block |
| C-c C-j  | Goto mode                                         |

#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-c a") 'org-agenda)
  (global-set-key (kbd "C-c o") (lambda ()
				  (interactive)
				  (find-file "~/org/buffers.org")))
  (global-set-key (kbd "C-c c") 'org-capture)
#+END_SRC

Use [[https://github.com/rexim/org-cliplink][org-cliplink]] to conveniently yank hyperlinks from clipboard, which
also supports automatic deduction of captions for the link.

*TODO*: this is temporarily disabled as cliplink may take too long to
analyze the url and get stuck. Use the old solution until this is
fixed.

#+BEGIN_SRC elisp
  (straight-use-package 'org-cliplink)
  (define-key org-mode-map (kbd "<f6>") 'org-cliplink)

  (defun custom-org-cliplink ()
    (interactive)
    (org-cliplink-insert-transformed-title
     (org-cliplink-clipboard-content)     ;take the URL from the CLIPBOARD
     (lambda (url title)
       (let* ((parsed-url (url-generic-parse-url url)) ;parse the url
              (clean-title
               (cond
                ;; if the host is github.com, cleanup the title
                ((string= (url-host parsed-url) "github.com")
                 (replace-regexp-in-string "GitHub - .*: \\(.*\\)" "\\1" title))
                ;; otherwise keep the original title
                (t title))))
         ;; forward the title to the default org-cliplink transformer
         (org-cliplink-org-mode-link-transformer url clean-title)))))
#+END_SRC

Old solution:

#+BEGIN_SRC emacs-lisp
  (defun bds/org/deduce-link-text (link)
      ;; TODO(breakds): Implement the actual logic here
      "here")
    (defun bds/org/yank-link ()
      (interactive)
      (let* ((link (current-kill 0))  ;; Get the front of the kill ring
             (text (bds/org/deduce-link-text link)))
        (insert "[[")
        (yank)
        (insert "][")
        (insert text)
        (insert "]]")))
  (define-key org-mode-map (kbd "<f6>") 'bds/org/yank-link)
#+END_SRC

* High-level Configuration

Display children with indentation level. Note that the indentation is
only *cosmetic*. 

#+BEGIN_SRC emacs-lisp
  (setq org-startup-indented t)
#+END_SRC

When save, save all org files in every buffer.

#+BEGIN_SRC emacs-lisp
  (add-hook 'after-save-hook 'org-save-all-org-buffers)
#+END_SRC

When displaying agenda, find tasks from the following files.

#+BEGIN_SRC emacs-lisp
  (setq org-agenda-files
        (cl-remove-if-not #'file-exists-p
                          (list "~/org/personal.org"
                                "~/org/buffers.org" 
                                "~/projects/Snippets/amazon.org")))
  (setq org-agenda-span 10)
  (setq org-agenda-start-on-weekday 0)
#+END_SRC

For visually better-looking org files in Emacs, we use [[https://github.com/integral-dw/org-bullets][org-bullets]].

#+BEGIN_SRC emacs-lisp
  (straight-use-package 'org-bullets)
  (add-hook 'org-mode-hook 
            (lambda () (org-bullets-mode 1)))
#+END_SRC

Enable =org-tempo= for easy-templates.

#+BEGIN_SRC emacs-lisp
  (require 'org-tempo)
#+END_SRC

* Cutomized Label And Tags

#+BEGIN_SRC emacs-lisp
  (setq org-todo-keywords
        '((sequence "TODO(t)" "ONGOING(g)" "PAUSE(p)" "|"
                    "DONE(d)" "DELEGATED(l)" "CANCELLED(c@)")))
  (setq org-todo-keyword-faces
        '(("ONGOING" . (:foreground "blue" :weight bold))
          ("PAUSE" . (:foreground "red" :weight bold))
          ("DELEGATED" . (:foreground "orange" :weight bold))))
  (setq org-tag-alist '((:startgroup . nil)
                        ("@work" . ?w)
                        ("@home" . ?h)
                        (:endgroup . nil)
                        ("FAVORITE" . ?f)))
#+END_SRC


* Markdown

Github Flavored Markdown exporter for org mode

#+BEGIN_SRC emacs-lisp
  (straight-use-package 'ox-gfm)
#+END_SRC

* Babel (Source code in org)

To make TAB work inside the source code blocks when the language is
determined (or specified).

#+BEGIN_SRC emacs-lisp
  (setq org-src-tab-acts-natively t)
#+END_SRC


* Org Capture

org-captured item by default goes to =buffers.org=.

#+BEGIN_SRC emacs-lisp
  (setq org-default-notes-file "~/org/buffers.org")
#+END_SRC

org-capture templates for different sub types.

#+BEGIN_SRC emacs-lisp
  (defun bds/habit-default-schedule ()
    (format-time-string "SCHEDULED: <%Y-%m-%d %a +7d>"))

  (setq org-capture-templates
        '(("t" "todo" entry (file+headline "~/org/buffers.org" "Tasks")
           "* TODO %?\n")
          ("f" "favorite" entry (file+headline "~/org/buffers.org" "Favorite")
           "* %? :FAVORITE:\n%a\n")
          ("h" "habit" entry (file+headline "~/org/buffers.org" "Tasks")
           "* TODO %? :HABIT:\n%(bds/habit-default-schedule)\n:PROPERTIES:\n:STYLE: habit\n:END:\n")))
#+END_SRC

* Refile

Targets include this file and any agenda file, up to 3 levels.

#+BEGIN_SRC emacs-lisp
  (setq org-refile-targets '((nil :maxlevel . 3)
                             (org-agenda-files :maxlevel . 3)
                             ("~/org/knowledge.org" :maxlevel . 2)))
#+END_SRC

However, targets with DONE state are EXCLUDED as refile targets.

#+BEGIN_SRC emacs-lisp
  (setq org-refile-target-verify-function
        (lambda ()
          (not (member (nth 2 (org-heading-components))
                       org-done-keywords))))
#+END_SRC


Refile to top-level is ALLOWED.
#+BEGIN_SRC emacs-lisp
  (setq org-refile-use-outline-path 'file)
#+END_SRC

Allow refile to create parent tasks with confirmation

#+BEGIN_SRC emacs-lisp
  (setq org-refile-allow-creating-parent-nodes 'confirm)
#+END_SRC


* Habit

#+BEGIN_SRC emacs-lisp
  (setq org-habit-show-habits-only-for-today nil)
#+END_SRC

* Archive
#+BEGIN_SRC emacs-lisp
  (defun bds/org-archive-all-done ()
    (interactive)
    (org-map-entries 'org-archive-subtree "/DONE/DELEGATED/CANCELLED" 'file))
#+END_SRC
